[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry~=1.0.5"]

[tool.poetry]
authors = ["James Curtin <jameswcurtin@gmail.com>"]
description = "Ameteur Radio Dashboard"
name = "ham-dash"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "0.61.2"
gunicorn = "20.0.4"
uvicorn = "0.12.3"


[tool.poetry.dev-dependencies]
black = "^20.8b0"
flake8 = "3.8.4"
isort = { version = "5.6.4", extras = ["pyproject"]}
pydocstyle = "5.1.1"
pytest = "6.1.2"
pytest-cov = '2.10.1'
requests = "^2.25.0"


[tool.black]
line-length = 88
target_version = ['py38']
exclude = '''
(
  /(
    \.git
    | \.mypy_cache
    | \.pytest_cache
    | htmlcov
    | venv
    | .venv
  )/
)
'''

[tool.isort]
profile = 'black'

[tool.coverage]
    [tool.coverage.run]
    source = ["app"]
    branch = true
    omit = ['']
    [tool.coverage.report]
    exclude_lines = [
        "# noqa",
        "raise NotImplementedError"
    ]
