name: Lint & Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cp .env.example .env
      - name: Lint
        run: docker-compose run --rm lint --check-only
      - name: Test
        run: docker-compose run --rm test
